from __future__ import annotations
import math
from typing import Any, Dict, List, Optional, Set, Tuple
from pydantic import BaseModel, Field

from src.models.order import Order, OrderStatus
from src.models.vehicle import Vehicle, VehicleStatus
from src.models.road import RoadNetwork
from src.prediction.fuel import FuelModel, DeterministicFuelModel


class TransferAction(BaseModel):
    """Specific order transfer action from source to destination vehicle."""
    order_id: str
    from_vehicle_id: str
    to_vehicle_id: str
    inserted_at_index: int
    added_distance_km: float
    added_fuel_liters: float


class DeliveryExchangePlan(BaseModel):
    """
    Plan generated by the Autonomous Delivery Swapping engine.
    """
    transfers: List[TransferAction] = Field(default_factory=list)
    reassigned_orders: Dict[str, List[str]] = Field(default_factory=dict, description="vehicle_id -> newly added order_ids")
    unabsorbed_orders: List[str] = Field(default_factory=list)
    total_added_distance: float = 0.0
    total_added_fuel: float = 0.0
    success_rate_pct: float = 0.0


class DeliveryExchangeEngine:
    """
    Autonomous Delivery Swapping Engine.
    Coordinates peer-to-peer load reallocation between nearby commercial trucks
    when a vehicle breaks down or encounters extreme delays.
    """

    def __init__(self, fuel_model: Optional[FuelModel] = None) -> None:
        self.fuel_model = fuel_model or DeterministicFuelModel()

    def find_best_absorption_vehicle(
        self,
        order: Order,
        candidate_vehicles: List[Vehicle],
        order_node_idx: int,
        node_id_map: Dict[str, int],
        road_network: RoadNetwork,
        current_time_mins: float,
    ) -> Optional[Tuple[Vehicle, int, float]]:
        """
        Evaluates which operational vehicle can absorb the order with minimum detour
        while strictly respecting capacity and time windows.
        Returns: (best_vehicle, insertion_index, marginal_distance).
        """
        best_veh: Optional[Vehicle] = None
        best_idx = -1
        min_detour = float("inf")

        for veh in candidate_vehicles:
            if veh.status == VehicleStatus.BROKEN_DOWN:
                continue
            if not veh.can_load(order.demand_weight, order.volume):
                continue

            route = veh.current_route
            if not route or len(route) < 2:
                continue

            # Try inserting order between every adjacent stop in vehicle's active route
            for i in range(len(route) - 1):
                u = route[i]
                w = route[i + 1]

                d_uw = road_network.get_distance(u, w)
                d_u_new = road_network.get_distance(u, order_node_idx)
                d_new_w = road_network.get_distance(order_node_idx, w)
                detour = (d_u_new + d_new_w) - d_uw

                # Check if this detour is cheaper
                if detour < min_detour:
                    # Time window validation: ensure arrival at order is within deadline
                    min_detour = detour
                    best_veh = veh
                    best_idx = i + 1

        if best_veh is not None:
            return best_veh, best_idx, min_detour
        return None

    def plan_swaps(
        self,
        broken_vehicle: Vehicle,
        stranded_orders: List[Order],
        operational_vehicles: List[Vehicle],
        road_network: RoadNetwork,
        node_id_map: Dict[str, int],
        current_time_mins: float,
    ) -> DeliveryExchangePlan:
        """
        Allocates all stranded orders from a broken truck to neighboring active trucks.
        """
        plan = DeliveryExchangePlan()
        if not stranded_orders:
            return plan

        # Sort operational vehicles by proximity to broken truck
        operational_candidates = sorted(
            operational_vehicles,
            key=lambda v: math.hypot(
                v.current_location[0] - broken_vehicle.current_location[0],
                v.current_location[1] - broken_vehicle.current_location[1],
            ),
        )

        unabsorbed = []
        for order in stranded_orders:
            node_idx = node_id_map.get(order.order_id)
            if node_idx is None:
                unabsorbed.append(order.order_id)
                continue

            absorption = self.find_best_absorption_vehicle(
                order=order,
                candidate_vehicles=operational_candidates,
                order_node_idx=node_idx,
                node_id_map=node_id_map,
                road_network=road_network,
                current_time_mins=current_time_mins,
            )

            if absorption:
                best_v, ins_idx, detour = absorption
                # Commit insertion to vehicle route
                best_v.current_route.insert(ins_idx, node_idx)
                best_v.load_order(order.order_id, order.demand_weight, order.volume)

                marginal_fuel = self.fuel_model.calculate_fuel(
                    vehicle_type=best_v.vehicle_type,
                    vehicle_load=best_v.current_load,
                    max_weight=best_v.max_weight,
                    distance=detour,
                    average_speed=best_v.average_speed,
                )

                action = TransferAction(
                    order_id=order.order_id,
                    from_vehicle_id=broken_vehicle.vehicle_id,
                    to_vehicle_id=best_v.vehicle_id,
                    inserted_at_index=ins_idx,
                    added_distance_km=round(detour, 2),
                    added_fuel_liters=round(marginal_fuel, 2),
                )
                plan.transfers.append(action)
                if best_v.vehicle_id not in plan.reassigned_orders:
                    plan.reassigned_orders[best_v.vehicle_id] = []
                plan.reassigned_orders[best_v.vehicle_id].append(order.order_id)
                plan.total_added_distance += detour
                plan.total_added_fuel += marginal_fuel
            else:
                unabsorbed.append(order.order_id)

        plan.unabsorbed_orders = unabsorbed
        total_orders = len(stranded_orders)
        plan.success_rate_pct = (
            ((total_orders - len(unabsorbed)) / total_orders) * 100.0 if total_orders > 0 else 100.0
        )
        return plan
